<Project>
  <!-- NuGet package metadata -->
  <PropertyGroup>
    <!-- License -->
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>

    <!-- Project information  -->
    <PackageProjectUrl>https://nullmake.github.io/calm-dotnet/</PackageProjectUrl>
    <RepositoryUrl>https://github.com/nullmake/calm-dotnet.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageReadmeFile>README.md</PackageReadmeFile>

    <!-- Package Icon -->
    <PackageIcon>icon.png</PackageIcon>
  </PropertyGroup>

  <!-- Accompany files -->
  <ItemGroup>
    <None Include="$(MSBuildThisFileDirectory)icon.png" Pack="true" PackagePath="/" Visible="false"/>
    <None Include="$(MSBuildThisFileDirectory)../../LICENSE" Pack="true" PackagePath="/" Visible="false"/>
    <None Include="$(MSBuildThisFileDirectory)../../README.md" Pack="true" PackagePath="/" Visible="false"/>
  </ItemGroup>
</Project>
