<Project>
  <!-- Common settings for all projects -->
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisLevel>latest</AnalysisLevel>
    <AnalysisMode>All</AnalysisMode>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <CodeAnalysisTreatWarningsAsErrors>true</CodeAnalysisTreatWarningsAsErrors>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release' and '$(TargetFrameworkIdentifier)' == '.NETFramework'">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>pdbonly</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release' and '$(TargetFrameworkIdentifier)' != '.NETFramework'">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>portable</DebugType>
  </PropertyGroup>

  <!-- Import Analyzer rules -->
  <ItemGroup>
    <GlobalAnalyzerConfigFiles Include="$(MSBuildThisFileDirectory).analyzer\dotnet.sdk.10.0.201.globalconfig" />
    <GlobalAnalyzerConfigFiles Include="$(MSBuildThisFileDirectory).analyzer\meziantou.analyzer.3.0.44.globalconfig" />
    <GlobalAnalyzerConfigFiles Include="$(MSBuildThisFileDirectory).analyzer\microsoft.visualstudio.threading.analyzers.17.14.15.globalconfig" />
    <GlobalAnalyzerConfigFiles Include="$(MSBuildThisFileDirectory).analyzer\roslynator.analyzers.4.15.0.globalconfig" />
    <GlobalAnalyzerConfigFiles Include="$(MSBuildThisFileDirectory).analyzer\sonaranalyzer.csharp.10.22.0.136894.globalconfig" />
    <GlobalAnalyzerConfigFiles Include="$(MSBuildThisFileDirectory).analyzer\StyleCop.Analyzers.globalconfig" />
    <AdditionalFiles Include="$(MSBuildThisFileDirectory).analyzer\StyleCop.json" Visible="false" />
  </ItemGroup>

  <!-- Assembly metadata -->
  <PropertyGroup>
    <Authors>nullmake</Authors>
    <Copyright>Copyright 2026 CALM Project</Copyright>
  </PropertyGroup>

  <!-- Deterministic Build -->
  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <Deterministic>true</Deterministic>
    <SlnRoot>$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)'))</SlnRoot>
    <PathMap>$(SlnRoot)=/_/</PathMap>
  </PropertyGroup>

  <!-- MinVer configuration -->
  <PropertyGroup>
    <MinVerTagPrefix>v</MinVerTagPrefix>
  </PropertyGroup>

  <!-- NuGet Packages -->
  <ItemGroup>
    <PackageReference Include="MinVer" Version="7.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="StyleCop.Analyzers" Version="1.1.118">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Meziantou.Analyzer" Version="3.0.48">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Threading.Analyzers" Version="17.14.15">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Roslynator.Analyzers" Version="4.15.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="SonarAnalyzer.CSharp" Version="10.23.0.137933">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>
